services:
  - type: web
    name: cortex-api
    runtime: docker
    dockerfile: ./Dockerfile
    rootDir: ./backend
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: HF_TOKEN
        sync: false

  - type: worker
    name: cortex-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    rootDir: ./backend
    plan: free
    dockerCommand: python run_worker.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: HF_TOKEN
        sync: false
