services:
  - type: web
    name: cortex-api
    runtime: docker
    dockerfile: ./Dockerfile
    rootDir: ./backend
    plan: free
    envVars:
      - name: QDRANT_API_KEY
        sync: false
      - name: QDRANT_URL
        sync: false
      - name: REDIS_URL
        sync: false
      - name: GROQ_API_KEY
        sync: false
      - name: GOOGLE_CLIENT_ID
        sync: false
      - name: JWT_SECRET
        sync: false
      - name: GITHUB_TOKEN
        sync: false

  - type: worker
    name: cortex-worker
    runtime: docker
    dockerfile: ./Dockerfile
    rootDir: ./backend
    plan: free
    dockerCommand: python run_worker.py
    envVars:
      - name: QDRANT_API_KEY
        sync: false
      - name: QDRANT_URL
        sync: false
      - name: REDIS_URL
        sync: false
      - name: GROQ_API_KEY
        sync: false
      - name: GOOGLE_CLIENT_ID
        sync: false
      - name: JWT_SECRET
        sync: false
      - name: GITHUB_TOKEN
        sync: false
